title: Milligan Mathematics
baseurl: "/courses"
url: "https://milligan-mathematics.github.io"

# Enable MathJax support via kramdown if desired, but we are using custom head for script 
kramdown:
  math_engine: mathjax
